export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';

export const INITIATED_DOWNLOAD = 'INITIATED_DOWNLOAD';
export const DOWNLOAD_QUEUED = 'DOWNLOAD_QUEUED';
export const DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS';
export const DOWNLOAD_COMPLETED = 'DOWNLOAD_COMPLETED';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DOWNLOAD_ERROR = 'DOWNLOAD_ERROR';
export const DELETE_ERROR = 'DELETE_ERROR';